apiVersion: v1

kind: Pod

metadata:
  name: react-app-pod
  labels: 
    component: web

spec:
  containers:
    - name: react-container
      image: ghostfreak077/simple_image
      ports:
        - containerPort: 3000


# munikube ip -> IP
# kubectl get service -> port